/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface NFTSpreadInterface extends utils.Interface {
  contractName: "NFTSpread";
  functions: {
    "INDEX_ID()": FunctionFragment;
    "deleteShares(address)": FunctionFragment;
    "distribute(uint256)": FunctionFragment;
    "gainShare(address,uint256)": FunctionFragment;
    "idaV1()": FunctionFragment;
    "loseShare(address)": FunctionFragment;
    "spreaderToken()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "INDEX_ID", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deleteShares",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "distribute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gainShare",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "idaV1", values?: undefined): string;
  encodeFunctionData(functionFragment: "loseShare", values: [string]): string;
  encodeFunctionData(
    functionFragment: "spreaderToken",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "INDEX_ID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deleteShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "distribute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gainShare", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "idaV1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "loseShare", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "spreaderToken",
    data: BytesLike
  ): Result;

  events: {};
}

export interface NFTSpread extends BaseContract {
  contractName: "NFTSpread";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: NFTSpreadInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    INDEX_ID(overrides?: CallOverrides): Promise<[number]>;

    "INDEX_ID()"(overrides?: CallOverrides): Promise<[number]>;

    deleteShares(
      subscriber: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "deleteShares(address)"(
      subscriber: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    distribute(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "distribute(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    gainShare(
      subscriber: string,
      units: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "gainShare(address,uint256)"(
      subscriber: string,
      units: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    idaV1(
      overrides?: CallOverrides
    ): Promise<[string, string] & { host: string; ida: string }>;

    "idaV1()"(
      overrides?: CallOverrides
    ): Promise<[string, string] & { host: string; ida: string }>;

    loseShare(
      subscriber: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "loseShare(address)"(
      subscriber: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    spreaderToken(overrides?: CallOverrides): Promise<[string]>;

    "spreaderToken()"(overrides?: CallOverrides): Promise<[string]>;
  };

  INDEX_ID(overrides?: CallOverrides): Promise<number>;

  "INDEX_ID()"(overrides?: CallOverrides): Promise<number>;

  deleteShares(
    subscriber: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "deleteShares(address)"(
    subscriber: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  distribute(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "distribute(uint256)"(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  gainShare(
    subscriber: string,
    units: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "gainShare(address,uint256)"(
    subscriber: string,
    units: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  idaV1(
    overrides?: CallOverrides
  ): Promise<[string, string] & { host: string; ida: string }>;

  "idaV1()"(
    overrides?: CallOverrides
  ): Promise<[string, string] & { host: string; ida: string }>;

  loseShare(
    subscriber: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "loseShare(address)"(
    subscriber: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  spreaderToken(overrides?: CallOverrides): Promise<string>;

  "spreaderToken()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    INDEX_ID(overrides?: CallOverrides): Promise<number>;

    "INDEX_ID()"(overrides?: CallOverrides): Promise<number>;

    deleteShares(subscriber: string, overrides?: CallOverrides): Promise<void>;

    "deleteShares(address)"(
      subscriber: string,
      overrides?: CallOverrides
    ): Promise<void>;

    distribute(amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "distribute(uint256)"(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    gainShare(
      subscriber: string,
      units: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "gainShare(address,uint256)"(
      subscriber: string,
      units: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    idaV1(
      overrides?: CallOverrides
    ): Promise<[string, string] & { host: string; ida: string }>;

    "idaV1()"(
      overrides?: CallOverrides
    ): Promise<[string, string] & { host: string; ida: string }>;

    loseShare(subscriber: string, overrides?: CallOverrides): Promise<void>;

    "loseShare(address)"(
      subscriber: string,
      overrides?: CallOverrides
    ): Promise<void>;

    spreaderToken(overrides?: CallOverrides): Promise<string>;

    "spreaderToken()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    INDEX_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "INDEX_ID()"(overrides?: CallOverrides): Promise<BigNumber>;

    deleteShares(
      subscriber: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "deleteShares(address)"(
      subscriber: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    distribute(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "distribute(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    gainShare(
      subscriber: string,
      units: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "gainShare(address,uint256)"(
      subscriber: string,
      units: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    idaV1(overrides?: CallOverrides): Promise<BigNumber>;

    "idaV1()"(overrides?: CallOverrides): Promise<BigNumber>;

    loseShare(
      subscriber: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "loseShare(address)"(
      subscriber: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    spreaderToken(overrides?: CallOverrides): Promise<BigNumber>;

    "spreaderToken()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    INDEX_ID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "INDEX_ID()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deleteShares(
      subscriber: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "deleteShares(address)"(
      subscriber: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    distribute(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "distribute(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    gainShare(
      subscriber: string,
      units: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "gainShare(address,uint256)"(
      subscriber: string,
      units: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    idaV1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "idaV1()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    loseShare(
      subscriber: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "loseShare(address)"(
      subscriber: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    spreaderToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "spreaderToken()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
